import { StyleSheet } from "react-native";
import { employeePalette } from "@syscor/shared/src/styles/employeePalette";
import { fonts } from "./fonts";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: employeePalette.bg,
  },
  filters: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
    paddingTop: 4,
    paddingHorizontal: 18,
    paddingBottom: 12,
  },
  filterPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: employeePalette.surface,
    borderWidth: 1,
    borderColor: employeePalette.line,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  filterPillActive: {
    backgroundColor: employeePalette.accent,
    borderColor: employeePalette.accent,
  },
  filterLabel: {
    fontFamily: fonts.mono,
    fontSize: 10,
    letterSpacing: 0.4,
    color: employeePalette.ink,
  },
  filterLabelActive: {
    color: "#FFFFFF",
  },
  list: {
    paddingHorizontal: 18,
    paddingBottom: 18,
    gap: 9,
    flexGrow: 1,
  },
  card: {
    backgroundColor: employeePalette.surface,
    borderWidth: 1,
    borderColor: employeePalette.line,
    borderRadius: 16,
    padding: 13,
    gap: 10,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  tableAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: employeePalette.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  tableAvatarNumber: {
    fontFamily: fonts.monoMedium,
    fontSize: 14,
    lineHeight: 16,
    color: "#FFFFFF",
    includeFontPadding: false,
  },
  tableAvatarLabel: {
    fontFamily: fonts.mono,
    fontSize: 6.5,
    lineHeight: 8,
    letterSpacing: 0.4,
    color: "#FFFFFF",
    includeFontPadding: false,
  },
  cardTexts: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  cardTitle: {
    fontFamily: fonts.sansBold,
    fontSize: 13.5,
    color: employeePalette.ink,
  },
  cardSubtitle: {
    fontFamily: fonts.sans,
    fontSize: 12,
    color: employeePalette.muted,
  },
  statusBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  statusLabel: {
    fontFamily: fonts.mono,
    fontSize: 10,
  },
  itemsBox: {
    backgroundColor: employeePalette.surface2,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 6,
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  itemQuantity: {
    minWidth: 22,
    fontFamily: fonts.monoMedium,
    fontSize: 12,
    color: employeePalette.muted,
  },
  itemName: {
    flex: 1,
    fontFamily: fonts.sans,
    fontSize: 12.5,
    color: employeePalette.ink,
  },
  itemPrice: {
    fontFamily: fonts.mono,
    fontSize: 12,
    color: employeePalette.ink,
  },
  notesRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 7,
  },
  notesText: {
    flex: 1,
    fontFamily: fonts.sans,
    fontStyle: "italic",
    fontSize: 12,
    color: employeePalette.ink,
  },
  cardFooter: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  totalLabel: {
    fontFamily: fonts.mono,
    fontSize: 10,
    letterSpacing: 0.6,
    color: employeePalette.muted,
  },
  totalAmount: {
    flex: 1,
    fontFamily: fonts.monoMedium,
    fontSize: 14,
    color: employeePalette.price,
  },
  deliverButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: employeePalette.accent,
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
    minWidth: 128,
    justifyContent: "center",
  },
  deliverButtonLabel: {
    fontFamily: fonts.sansBold,
    fontSize: 12.5,
    color: "#FFFFFF",
  },
  stateBox: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 40,
    paddingHorizontal: 24,
  },
  stateText: {
    fontFamily: fonts.sans,
    fontSize: 13,
    color: employeePalette.muted,
    textAlign: "center",
  },
  errorText: {
    fontFamily: fonts.sansMedium,
    fontSize: 12,
    color: employeePalette.warnText,
    marginHorizontal: 18,
    marginBottom: 10,
  },
});
