import { StyleSheet } from 'react-native';

export const COLORS = {
  primary: '#C62828',
  bg: '#FDFBF7',
  dark: '#221510',
  text: '#1E1E1E',
  gray: '#8A8A8A',
  border: '#EDEAE4',
  white: '#FFFFFF',
  green: '#2E7D32',
  greenLight: '#DCF5D0',
};

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.bg,
    padding: 24,
  },
  errorText: {
    fontSize: 15,
    color: COLORS.text,
    textAlign: 'center',
    marginBottom: 16,
  },
  retryButton: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 10,
  },
  retryButtonText: {
    color: COLORS.white,
    fontWeight: '700',
  },
  scrollContent: {
    paddingBottom: 140,
  },
  imageContainer: {
    backgroundColor: COLORS.dark,
    height: 300,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  productImage: {
    width: '85%',
    height: 220,
    resizeMode: 'contain',
    marginBottom: 12,
  },
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 40,
    zIndex: 10,
  },
  headerButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerIcon: {
    fontSize: 18,
    color: '#FF6B5E',
    fontWeight: '700',
  },
  infoContainer: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  name: {
    fontSize: 28,
    fontWeight: '800',
    color: COLORS.text,
  },
  price: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.primary,
    marginTop: 4,
  },
  description: {
    fontSize: 14,
    lineHeight: 21,
    color: COLORS.gray,
    marginTop: 10,
  },
  section: {
    paddingHorizontal: 20,
    marginTop: 26,
  },
  sectionContainer: {
    paddingHorizontal: 20,
    marginTop: 26,
  },
  listContainer: {
    marginTop: 4,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 1,
    color: COLORS.text,
  },
  sectionTitleNormal: {
    fontSize: 17,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: 12,
  },
  requiredBadge: {
    backgroundColor: COLORS.greenLight,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 3,
    marginLeft: 10,
  },
  requiredText: {
    fontSize: 10,
    fontWeight: '800',
    color: COLORS.green,
    letterSpacing: 0.5,
  },
  requiredSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  requiredSectionHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 1,
  },
  chevron: {
    fontSize: 16,
    color: COLORS.gray,
    marginLeft: 8,
  },
  requiredSubtitle: {
    fontSize: 13,
    color: COLORS.gray,
    marginTop: 2,
    marginBottom: 8,
  },
  plainListContainer: {
    marginTop: 4,
  },
  chipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  tortillaChip: {
    flex: 1,
  },
  salsasRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 24,
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  addButton: {
    flex: 1,
    marginLeft: 12,
    backgroundColor: COLORS.primary,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  addButtonText: {
    color: COLORS.white,
    fontSize: 13,
    fontWeight: '800',
    flex: 1,
    marginRight: 8,
  },
  addButtonPrice: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '800',
  },
});